### ISSUE TITLE
Can't push branch on MacOS

### ISSUE THREAD

**Issue by GreatWizard** [njoyard/realease#2]
When we try to make a release on MacOS, it's hanging forever on the push command.

Here is a tiny copy a  terminal.
There is no error displays in the terminal.

```sh
yarn realease minor
yarn run v1.15.2
$ /Users/.../node_modules/.bin/realease minor
Updating package.json to version 2.1.0
Creating release branch release/2.1.0
Creating release commit with message Release version 2.1.0
Pushing branch release/2.1.0 to origin
```

**Comment by njoyard** [comment]
* Do you have a SSH agent? Does `$SSH_AUTH_SOCK` have a value?
* Do you have a newer format openssh key? You can tell by running `head -n 1 ~/.ssh/id_rsa`, if it reads `-----BEGIN OPENSSH PRIVATE KEY-----` (not `RSA`) then you do (and nodegit does not work with them, you need a key generated in PEM format)

**Comment by GreatWizard** [comment]
About SSH Agent it seems ok:
>▶ echo $SSH_AUTH_SOCK
> /private/tmp/com.apple.launchd.GcczkdCrjx/Listeners

About openssh key, I have a RSA Key (`-----BEGIN RSA PRIVATE KEY-----`)

**Comment by njoyard** [comment]
Can you ensure your key is added to the agent keychain and retry? `ssh-add -K /path/to/privatekey`

**Comment by GreatWizard** [comment]
IT WORKS, thanks you! we must definitively add this in the readme

**Comment by njoyard** [comment]
Done https://github.com/njoyard/realease/commit/374b9b3c0ca2c58e2e9b8fde5ba6d52b5bbbe60b
