### ISSUE TITLE
About generating CHANGELOG.md

### ISSUE THREAD

**Issue by BlueCutOfficial** [njoyard/realease#4]
I don't know how many projects have this problem. 
Before `realease` set up, using `npm version` generated new entries in CHANGELOG.md. 
`package.json` contain the following command: 
``` 
"preversion": "sh scripts/changelog.sh $npm_package_version"
```
From my understanding `npm version` read the old version number in `pakage.json` and generated the changelog for the new version based on the commit after the old version, then only then the version number of `pakage.json` is updated. 

Do you think the need of `preversion` command is generic enough to be integrated in `realease` process?

**Comment by njoyard** [comment]
Maybe we could use "npm version" to bump the version number...
